/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Helper.Auth;
import Helper.MsgBox;
import Helper.XImage;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URL; 
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author 84985
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.init();

    }

    private void init() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(XImage.getAPPIcon());
        new ChaoDialog(this, true).setVisible(true);
        new DangNhapDialog(this, true).setVisible(true);
        MainFrame that = this;
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");
                Date d = new Date();
                that.lbldongho.setText(sdf.format(d));
            }
        }).start();
    }

    void dangXuat() {
        if (MsgBox.confirm(this, "Bạn có muốn Đăng Xuất không")) {
            Auth.clear();
            MsgBox.alert(this, "Đăng Xuất Thành công");
        }
    }

    void doimk() {
        if (!Auth.islogin()) {
            MsgBox.alert(this, "Bạn chưa Đăng Nhập");
        } else {
            new DOiMatKhauDialog(this, true).setVisible(true);
        }
    }

    void keThuc() {
        if (MsgBox.confirm(this, "Bạn có muốn Thoát không")) {
            System.exit(0);
        }
    }

    void openChuyenDe() {
        if (!Auth.islogin()) {
            MsgBox.alert(this, "Bạn Chưa Đăng Nhập");
        } else {
            new QuanLyCHuyenDeDialog(this, true).setVisible(true);
        }
    }

    void openNguoiHoc() {
        if (!Auth.islogin()) {
            MsgBox.alert(this, "Bạn Chưa Đăng Nhập");
        } else {
            new NguoiHocDialog(this, true).setVisible(true);
        }
    }

    void openNhanVien() {
        if (!Auth.islogin()) {
            MsgBox.alert(this, "Bạn Chưa Đăng Nhập");
        } else {
            new NhanVienDialog(this, true).setVisible(true);
        }
    }

    void openHocVien() {
        if (!Auth.islogin()) {
            MsgBox.alert(this, "Bạn Chưa Đăng Nhập");
        } else {
            new HocVienDialog(this, true).setVisible(true);
        }
    }

    void openKhoaHoc() {
        if (!Auth.islogin()) {
            MsgBox.alert(this, "Bạn Chưa Đăng Nhập");
        } else {
            new KhoaHocDialog(this, true).setVisible(true);
        }
    }

    void openGioiThieu() {
        new GioiThieuDialog(this, true).setVisible(true);
    }

    void openThongKe(int index) {
        if (!Auth.islogin()) {
            MsgBox.alert(this, "Bạn Chưa Đăng Nhập");
        } else {
            if(!Auth.isManager()&& index == 3){
                MsgBox.alert(this, "Chỉ Trưởng Phòng mới được xem");
            }else{
                ThongKeDialog tk = new ThongKeDialog(this, true);
            tk.setVisible(true);
            tk.selectTab(index);
            }
                  
        }
    } 
    
    void openHuongDan(){
        try {
               Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (IOException e) {
         MsgBox.alert(this, "Không tìm thấy file Hướng Dẫn");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btndangxuat = new javax.swing.JButton();
        btnketthuc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnchuyende = new javax.swing.JButton();
        btnkhoahoc = new javax.swing.JButton();
        btnnguoihoc = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnhuongdan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuhethong = new javax.swing.JMenu();
        mnidangnhap = new javax.swing.JMenuItem();
        mnidangxuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnidoimk = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniketthuc = new javax.swing.JMenuItem();
        mnuquanly = new javax.swing.JMenu();
        mninguoihoc = new javax.swing.JMenuItem();
        mmnichuyende = new javax.swing.JMenuItem();
        mnikhoahoc = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniqlnhanvien = new javax.swing.JMenuItem();
        mnuthongke = new javax.swing.JMenu();
        mniNHTN = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniBDK = new javax.swing.JMenuItem();
        mniDTK = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniDTCD = new javax.swing.JMenuItem();
        mntrogiup = new javax.swing.JMenu();
        mniHDSD = new javax.swing.JMenuItem();
        mniGTSPP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ QUẢN LÝ ĐÀO TẠO");

        jToolBar1.setRollover(true);

        btndangxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        btndangxuat.setText("Đăng Xuất");
        btndangxuat.setFocusable(false);
        btndangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndangxuat.setMargin(new java.awt.Insets(2, 30, 2, 14));
        btndangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btndangxuat);

        btnketthuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        btnketthuc.setText("Kết Thúc");
        btnketthuc.setFocusable(false);
        btnketthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnketthuc.setMargin(new java.awt.Insets(2, 30, 2, 14));
        btnketthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketthucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnketthuc);
        jToolBar1.add(jSeparator2);

        btnchuyende.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
        btnchuyende.setText("Chuyên Đề");
        btnchuyende.setFocusable(false);
        btnchuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnchuyende.setMargin(new java.awt.Insets(2, 30, 2, 14));
        btnchuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnchuyende);

        btnkhoahoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnkhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Certificate.png"))); // NOI18N
        btnkhoahoc.setText("Khóa Học");
        btnkhoahoc.setFocusable(false);
        btnkhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkhoahoc.setMargin(new java.awt.Insets(2, 30, 2, 14));
        btnkhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnkhoahoc);

        btnnguoihoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Conference.png"))); // NOI18N
        btnnguoihoc.setText("Người Học");
        btnnguoihoc.setFocusable(false);
        btnnguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnguoihoc.setMargin(new java.awt.Insets(2, 30, 2, 14));
        btnnguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnguoihocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnguoihoc);
        jToolBar1.add(jSeparator4);

        btnhuongdan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnhuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Globe.png"))); // NOI18N
        btnhuongdan.setText("Hướng Dẫn");
        btnhuongdan.setFocusable(false);
        btnhuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhuongdan.setMargin(new java.awt.Insets(2, 30, 2, 14));
        btnhuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuongdanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnhuongdan);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Info.png"))); // NOI18N
        jLabel1.setText("Hệ quản lý đào tạo");

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinhNen.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 607, Short.MAX_VALUE)
        );

        lbldongho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alarm.png"))); // NOI18N
        lbldongho.setText("jLabel2");

        mnuhethong.setText("Hệ Thống");
        mnuhethong.setMargin(new java.awt.Insets(0, 10, 0, 0));

        mnidangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnidangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Key.png"))); // NOI18N
        mnidangnhap.setText("Đăng Nhập");
        mnidangnhap.setMargin(new java.awt.Insets(15, 0, 0, 0));
        mnidangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangnhapActionPerformed(evt);
            }
        });
        mnuhethong.add(mnidangnhap);

        mnidangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnidangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        mnidangxuat.setText("Đăng Xuất");
        mnidangxuat.setMargin(new java.awt.Insets(15, 0, 0, 0));
        mnidangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangxuatActionPerformed(evt);
            }
        });
        mnuhethong.add(mnidangxuat);
        mnuhethong.add(jSeparator1);

        mnidoimk.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnidoimk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        mnidoimk.setText("Đổi Mật Khẩu");
        mnidoimk.setMargin(new java.awt.Insets(15, 0, 0, 0));
        mnidoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidoimkActionPerformed(evt);
            }
        });
        mnuhethong.add(mnidoimk);
        mnuhethong.add(jSeparator3);

        mniketthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mniketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        mniketthuc.setText("Kết Thúc");
        mniketthuc.setMargin(new java.awt.Insets(15, 0, 0, 0));
        mniketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniketthucActionPerformed(evt);
            }
        });
        mnuhethong.add(mniketthuc);

        jMenuBar1.add(mnuhethong);

        mnuquanly.setText("Quản lý");
        mnuquanly.setMargin(new java.awt.Insets(0, 10, 0, 0));

        mninguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mninguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Conference.png"))); // NOI18N
        mninguoihoc.setText("Người Học");
        mninguoihoc.setMargin(new java.awt.Insets(15, 0, 0, 0));
        mninguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninguoihocActionPerformed(evt);
            }
        });
        mnuquanly.add(mninguoihoc);

        mmnichuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mmnichuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
        mmnichuyende.setText("Chuyên Đề");
        mmnichuyende.setMargin(new java.awt.Insets(15, 0, 0, 0));
        mmnichuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmnichuyendeActionPerformed(evt);
            }
        });
        mnuquanly.add(mmnichuyende);

        mnikhoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnikhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Certificate.png"))); // NOI18N
        mnikhoahoc.setText("Khóa Học");
        mnikhoahoc.setMargin(new java.awt.Insets(15, 0, 0, 0));
        mnikhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnikhoahocActionPerformed(evt);
            }
        });
        mnuquanly.add(mnikhoahoc);
        mnuquanly.add(jSeparator5);

        mniqlnhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mniqlnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User group.png"))); // NOI18N
        mniqlnhanvien.setText("Quản lý nhân viên");
        mniqlnhanvien.setMargin(new java.awt.Insets(15, 0, 0, 0));
        mniqlnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniqlnhanvienActionPerformed(evt);
            }
        });
        mnuquanly.add(mniqlnhanvien);

        jMenuBar1.add(mnuquanly);

        mnuthongke.setText("Thống kê");
        mnuthongke.setMargin(new java.awt.Insets(0, 10, 0, 0));

        mniNHTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mniNHTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clien list.png"))); // NOI18N
        mniNHTN.setText("Người học từng năm");
        mniNHTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNHTNActionPerformed(evt);
            }
        });
        mnuthongke.add(mniNHTN);
        mnuthongke.add(jSeparator6);

        mniBDK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mniBDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Card file.png"))); // NOI18N
        mniBDK.setText("Bảng Điểm Khóa");
        mniBDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBDKActionPerformed(evt);
            }
        });
        mnuthongke.add(mniBDK);

        mniDTK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mniDTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Best.png"))); // NOI18N
        mniDTK.setText("Điểm Từng khóa");
        mniDTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDTKActionPerformed(evt);
            }
        });
        mnuthongke.add(mniDTK);
        mnuthongke.add(jSeparator7);

        mniDTCD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mniDTCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dollar.png"))); // NOI18N
        mniDTCD.setText("Doanh Thu Từng Chuyên Đề");
        mniDTCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDTCDActionPerformed(evt);
            }
        });
        mnuthongke.add(mniDTCD);

        jMenuBar1.add(mnuthongke);

        mntrogiup.setText("Trợ giúp");
        mntrogiup.setMargin(new java.awt.Insets(0, 10, 0, 0));

        mniHDSD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        mniHDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Globe.png"))); // NOI18N
        mniHDSD.setText("Hướng dẫn sử dụng");
        mniHDSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHDSDActionPerformed(evt);
            }
        });
        mntrogiup.add(mniHDSD);

        mniGTSPP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        mniGTSPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home.png"))); // NOI18N
        mniGTSPP.setText("Giới Thiệu sản phẩm");
        mniGTSPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGTSPPActionPerformed(evt);
            }
        });
        mntrogiup.add(mniGTSPP);

        jMenuBar1.add(mntrogiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldongho)
                    .addComponent(jLabel1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuongdanActionPerformed
        this.openHuongDan();
    }//GEN-LAST:event_btnhuongdanActionPerformed

    private void mnidangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangxuatActionPerformed
        this.dangXuat();
    }//GEN-LAST:event_mnidangxuatActionPerformed

    private void mniketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniketthucActionPerformed
        this.keThuc();
    }//GEN-LAST:event_mniketthucActionPerformed

    private void mnikhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnikhoahocActionPerformed
      this.openKhoaHoc();
    }//GEN-LAST:event_mnikhoahocActionPerformed

    private void mnidoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidoimkActionPerformed
        this.doimk();
    }//GEN-LAST:event_mnidoimkActionPerformed

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
        this.dangXuat();
    }//GEN-LAST:event_btndangxuatActionPerformed

    private void btnketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketthucActionPerformed
        this.keThuc();
    }//GEN-LAST:event_btnketthucActionPerformed

    private void btnchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyendeActionPerformed
       this.openChuyenDe();
    }//GEN-LAST:event_btnchuyendeActionPerformed

    private void btnkhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoahocActionPerformed
       this.openKhoaHoc();
    }//GEN-LAST:event_btnkhoahocActionPerformed

    private void btnnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnguoihocActionPerformed
       this.openNguoiHoc();
    }//GEN-LAST:event_btnnguoihocActionPerformed

    private void mninguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninguoihocActionPerformed
       this.openNguoiHoc();
    }//GEN-LAST:event_mninguoihocActionPerformed

    private void mmnichuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmnichuyendeActionPerformed
       this.openChuyenDe();
    }//GEN-LAST:event_mmnichuyendeActionPerformed

    private void mniqlnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniqlnhanvienActionPerformed
        this.openNhanVien();
    }//GEN-LAST:event_mniqlnhanvienActionPerformed

    private void mniNHTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNHTNActionPerformed
       this.openThongKe(0);
    }//GEN-LAST:event_mniNHTNActionPerformed

    private void mniBDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBDKActionPerformed
       this.openThongKe(1);
    }//GEN-LAST:event_mniBDKActionPerformed

    private void mniDTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDTKActionPerformed
      this.openThongKe(2);
    }//GEN-LAST:event_mniDTKActionPerformed

    private void mniDTCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDTCDActionPerformed
       this.openThongKe(3);
    }//GEN-LAST:event_mniDTCDActionPerformed

    private void mnidangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangnhapActionPerformed
        if(Auth.islogin()){
            MsgBox.alert(this, "Bạn đăng nhập với Mã Tài Khoản: "+Auth.user.getMaNV());
        }else{
            new DangNhapDialog(this,true).setVisible(true);
        }
    }//GEN-LAST:event_mnidangnhapActionPerformed

    private void mniHDSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHDSDActionPerformed
        this.openHuongDan();
    }//GEN-LAST:event_mniHDSDActionPerformed

    private void mniGTSPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGTSPPActionPerformed
       this.openGioiThieu();
    }//GEN-LAST:event_mniGTSPPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchuyende;
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btnhuongdan;
    private javax.swing.JButton btnketthuc;
    private javax.swing.JButton btnkhoahoc;
    private javax.swing.JButton btnnguoihoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JMenuItem mmnichuyende;
    private javax.swing.JMenuItem mniBDK;
    private javax.swing.JMenuItem mniDTCD;
    private javax.swing.JMenuItem mniDTK;
    private javax.swing.JMenuItem mniGTSPP;
    private javax.swing.JMenuItem mniHDSD;
    private javax.swing.JMenuItem mniNHTN;
    private javax.swing.JMenuItem mnidangnhap;
    private javax.swing.JMenuItem mnidangxuat;
    private javax.swing.JMenuItem mnidoimk;
    private javax.swing.JMenuItem mniketthuc;
    private javax.swing.JMenuItem mnikhoahoc;
    private javax.swing.JMenuItem mninguoihoc;
    private javax.swing.JMenuItem mniqlnhanvien;
    private javax.swing.JMenu mntrogiup;
    private javax.swing.JMenu mnuhethong;
    private javax.swing.JMenu mnuquanly;
    private javax.swing.JMenu mnuthongke;
    // End of variables declaration//GEN-END:variables

}
